# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contract_processed.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x18\x63ontract_processed.proto"\xfd\x01\n\x11\x43ontractProcessed\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x19\n\x11\x63reated_timestamp\x18\x03 \x01(\x03\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x10\n\x08is_token\x18\x05 \x01(\x08\x12\x1e\n\x16\x63ontract_updated_block\x18\x06 \x01(\x03\x12\x15\n\rcontract_type\x18\x07 \x01(\t\x12\x16\n\x0etoken_standard\x18\x08 \x01(\t\x12\x0e\n\x06symbol\x18\t \x01(\t\x12\x18\n\x10transaction_hash\x18\x0f \x01(\t\x12\x13\n\x0bis_creation\x18\x10 \x01(\x08\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "contract_processed_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _CONTRACTPROCESSED._serialized_start = 29
    _CONTRACTPROCESSED._serialized_end = 282
# @@protoc_insertion_point(module_scope)
