"""add social media

Revision ID: 2aa5980d281a
Revises: a18d3f9eb720
Create Date: 2022-01-27 23:13:08.138322

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "2aa5980d281a"
down_revision = "a18d3f9eb720"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "social_medias",
        sa.Column("contract_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("team_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("short_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("long_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("p_rep_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("website", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("license", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("facebook", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("telegram", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("reddit", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("discord", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("steemit", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("twitter", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("youtube", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("github", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("keybase", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("wechat", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("contract_address"),
    )
    op.create_index(
        op.f("ix_social_medias_contract_address"),
        "social_medias",
        ["contract_address"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_social_medias_contract_address"), table_name="social_medias")
    op.drop_table("social_medias")
    # ### end Alembic commands ###
