"""init

Revision ID: 32ea6426c188
Revises: 
Create Date: 2021-09-22 15:02:10.555106

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '32ea6426c188'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('p2p_endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('node_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_address'), 'contract', ['address'], unique=False)
    op.create_index(op.f('ix_contract_city'), 'contract', ['city'], unique=False)
    op.create_index(op.f('ix_contract_country'), 'contract', ['country'], unique=False)
    op.create_index(op.f('ix_contract_details'), 'contract', ['details'], unique=False)
    op.create_index(op.f('ix_contract_email'), 'contract', ['email'], unique=False)
    op.create_index(op.f('ix_contract_id'), 'contract', ['id'], unique=False)
    op.create_index(op.f('ix_contract_name'), 'contract', ['name'], unique=False)
    op.create_index(op.f('ix_contract_node_address'), 'contract', ['node_address'], unique=False)
    op.create_index(op.f('ix_contract_p2p_endpoint'), 'contract', ['p2p_endpoint'], unique=False)
    op.create_index(op.f('ix_contract_website'), 'contract', ['website'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_website'), table_name='contract')
    op.drop_index(op.f('ix_contract_p2p_endpoint'), table_name='contract')
    op.drop_index(op.f('ix_contract_node_address'), table_name='contract')
    op.drop_index(op.f('ix_contract_name'), table_name='contract')
    op.drop_index(op.f('ix_contract_id'), table_name='contract')
    op.drop_index(op.f('ix_contract_email'), table_name='contract')
    op.drop_index(op.f('ix_contract_details'), table_name='contract')
    op.drop_index(op.f('ix_contract_country'), table_name='contract')
    op.drop_index(op.f('ix_contract_city'), table_name='contract')
    op.drop_index(op.f('ix_contract_address'), table_name='contract')
    op.drop_table('contract')
    # ### end Alembic commands ###
