"""add nft columns

Revision ID: 80b5d1f25196
Revises: 2aa5980d281a
Create Date: 2022-06-11 11:01:39.886765

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "80b5d1f25196"
down_revision = "2aa5980d281a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contracts", sa.Column("is_nft", sa.Boolean(), nullable=True))
    op.create_index(op.f("ix_contracts_is_nft"), "contracts", ["is_nft"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_contracts_is_nft"), table_name="contracts")
    op.drop_column("contracts", "is_nft")
    # ### end Alembic commands ###
