"""add contract verification

Revision ID: a18d3f9eb720
Revises: a6de39712a88
Create Date: 2022-01-26 16:53:50.039641

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "a18d3f9eb720"
down_revision = "a6de39712a88"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("kafka_jobs")
    op.add_column(
        "contracts",
        sa.Column("verified_source_code_link", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column("contracts", sa.Column("verified", sa.Boolean(), nullable=True))
    op.create_index(op.f("ix_contracts_verified"), "contracts", ["verified"], unique=False)
    op.drop_column("contracts", "country")
    op.drop_column("contracts", "city")
    op.drop_column("contracts", "details")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contracts", sa.Column("details", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column("contracts", sa.Column("city", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column(
        "contracts", sa.Column("country", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f("ix_contracts_verified"), table_name="contracts")
    op.drop_column("contracts", "verified")
    op.drop_column("contracts", "verified_source_code_link")
    op.create_table(
        "kafka_jobs",
        sa.Column("job_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("worker_group", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("topic", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("partition", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("stop_offset", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "job_id", "worker_group", "topic", "partition", name="kafka_jobs_pkey"
        ),
    )
    # ### end Alembic commands ###
