"""init

Revision ID: a95c0b4e2c3a
Revises:
Create Date: 2021-09-28 10:57:35.953408

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "a95c0b4e2c3a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contract",
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("website", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("details", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("p2p_endpoint", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("node_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_updated_block", sa.Integer(), nullable=True),
        sa.Column("last_updated_timestamp", sa.Integer(), nullable=True),
        sa.Column("created_block", sa.Integer(), nullable=True),
        sa.Column("created_timestamp", sa.Integer(), nullable=True),
        sa.Column("current_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("address"),
    )
    op.create_index(op.f("ix_contract_address"), "contract", ["address"], unique=False)
    op.create_index(op.f("ix_contract_city"), "contract", ["city"], unique=False)
    op.create_index(op.f("ix_contract_country"), "contract", ["country"], unique=False)
    op.create_index(op.f("ix_contract_created_block"), "contract", ["created_block"], unique=False)
    op.create_index(
        op.f("ix_contract_created_timestamp"), "contract", ["created_timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_contract_current_version"), "contract", ["current_version"], unique=False
    )
    op.create_index(op.f("ix_contract_details"), "contract", ["details"], unique=False)
    op.create_index(op.f("ix_contract_email"), "contract", ["email"], unique=False)
    op.create_index(
        op.f("ix_contract_last_updated_block"), "contract", ["last_updated_block"], unique=False
    )
    op.create_index(
        op.f("ix_contract_last_updated_timestamp"),
        "contract",
        ["last_updated_timestamp"],
        unique=False,
    )
    op.create_index(op.f("ix_contract_name"), "contract", ["name"], unique=False)
    op.create_index(op.f("ix_contract_node_address"), "contract", ["node_address"], unique=False)
    op.create_index(op.f("ix_contract_p2p_endpoint"), "contract", ["p2p_endpoint"], unique=False)
    op.create_index(op.f("ix_contract_status"), "contract", ["status"], unique=False)
    op.create_index(op.f("ix_contract_website"), "contract", ["website"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_contract_website"), table_name="contract")
    op.drop_index(op.f("ix_contract_status"), table_name="contract")
    op.drop_index(op.f("ix_contract_p2p_endpoint"), table_name="contract")
    op.drop_index(op.f("ix_contract_node_address"), table_name="contract")
    op.drop_index(op.f("ix_contract_name"), table_name="contract")
    op.drop_index(op.f("ix_contract_last_updated_timestamp"), table_name="contract")
    op.drop_index(op.f("ix_contract_last_updated_block"), table_name="contract")
    op.drop_index(op.f("ix_contract_email"), table_name="contract")
    op.drop_index(op.f("ix_contract_details"), table_name="contract")
    op.drop_index(op.f("ix_contract_current_version"), table_name="contract")
    op.drop_index(op.f("ix_contract_created_timestamp"), table_name="contract")
    op.drop_index(op.f("ix_contract_created_block"), table_name="contract")
    op.drop_index(op.f("ix_contract_country"), table_name="contract")
    op.drop_index(op.f("ix_contract_city"), table_name="contract")
    op.drop_index(op.f("ix_contract_address"), table_name="contract")
    op.drop_table("contract")
    # ### end Alembic commands ###
