"""init

Revision ID: aef5033f1f49
Revises:
Create Date: 2021-10-07 21:01:23.889952

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "aef5033f1f49"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contracts",
        sa.Column("last_updated_timestamp", sa.BIGINT(), nullable=True),
        sa.Column("created_timestamp", sa.BIGINT(), nullable=True),
        sa.Column("abi", sa.JSON(), nullable=True),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("symbol", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("decimals", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("contract_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("website", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("details", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_updated_block", sa.Integer(), nullable=True),
        sa.Column("created_block", sa.Integer(), nullable=True),
        sa.Column("owner_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("current_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_code_link", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("revision_number", sa.Integer(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_token", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("address"),
    )
    op.create_index(op.f("ix_contracts_address"), "contracts", ["address"], unique=False)
    op.create_index(
        op.f("ix_contracts_contract_type"), "contracts", ["contract_type"], unique=False
    )
    op.create_index(
        op.f("ix_contracts_created_block"), "contracts", ["created_block"], unique=False
    )
    op.create_index(op.f("ix_contracts_is_token"), "contracts", ["is_token"], unique=False)
    op.create_index(
        op.f("ix_contracts_last_updated_block"), "contracts", ["last_updated_block"], unique=False
    )
    op.create_index(
        op.f("ix_contracts_owner_address"), "contracts", ["owner_address"], unique=False
    )
    op.create_index(op.f("ix_contracts_status"), "contracts", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_contracts_status"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_owner_address"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_last_updated_block"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_is_token"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_created_block"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_contract_type"), table_name="contracts")
    op.drop_index(op.f("ix_contracts_address"), table_name="contracts")
    op.drop_table("contracts")
    # ### end Alembic commands ###
