"""add score status fields

Revision ID: db64f1e0f613
Revises: 038b6ed909a1
Create Date: 2022-10-11 17:30:08.685237

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "db64f1e0f613"
down_revision = "038b6ed909a1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contracts", sa.Column("audit_tx_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "contracts", sa.Column("code_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.add_column(
        "contracts", sa.Column("deploy_tx_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contracts", "deploy_tx_hash")
    op.drop_column("contracts", "code_hash")
    op.drop_column("contracts", "audit_tx_hash")
    # ### end Alembic commands ###
